### ISSUE TITLE
Trezor T BOM and schematic mismatch

### ISSUE THREAD

**Issue by micmys** [trezor/trezor-hardware#26]
I noticed there are differences in the BOM for Trezor model T:
https://github.com/trezor/trezor-hardware/blob/master/electronics/trezor_model_t/bom.txt
and its schematic:
https://github.com/trezor/trezor-hardware/blob/master/electronics/trezor_model_t/schematic.png

For example:
- transistors T1/T2 with their accompanying components are absent in the BOM
- IC1 is also nowhere to be found
- resistors R9, R10 have different values in both documents
- (probably some more discrepancies)

I assume that the schematic is newer & correct and BOM should be adjusted, but this probably needs clarification.

**Comment by prusnak** [comment]
BOM updated in https://github.com/trezor/trezor-hardware/commit/5e020e14b6635fb0b783444121c7a3eb60352929
